### ISSUE TITLE
Cannot build 2.4.3 on Raspberry Pi 5

### ISSUE THREAD

**Issue by tspannhw** [milvus-io/milvus-lite#155]
======== Input profiles ========
Profile host:
[settings]
arch=armv8
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

Profile build:
[settings]
arch=armv8
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

ERROR: Error loading conanfile at '/opt/demo/milvus-lite/conanfile.py': Unable to load conanfile in /opt/demo/milvus-lite/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/demo/milvus-lite/conanfile.py", line 1, in <module>
    from conans import ConanFile
ImportError: cannot import name 'ConanFile' from 'conans' (/home/tspann/milvusvenv/lib/python3.11/site-packages/conans/__init__.py)

Traceback (most recent call last):
  File "/opt/demo/milvus-lite/python/setup.py", line 146, in <module>
    setup(name='milvus-lite',
  File "/home/tspann/milvusvenv/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tspann/milvusvenv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/home/tspann/milvusvenv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/home/tspann/milvusvenv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/tspann/milvusvenv/lib/python3.11/site-packages/setuptools/dist.py", line 968, in run_command
    super().run_command(command)
  File "/home/tspann/milvusvenv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/demo/milvus-lite/python/setup.py", line 101, in run
    subprocess.check_call(['conan', 'install', extdir, '--build=missing', '-s', 'build_type=Release', '-s', 'compiler.libcxx=libstdc++11'],
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conan', 'install', '/opt/demo/milvus-lite', '--build=missing', '-s', 'build_type=Release', '-s', 'compiler.libcxx=libstdc++11']' returned non-zero exit status 1.
(milvusvenv) root@five:/opt/demo/milvus-lite/python# python3 setup.py bdist_wheel

**Comment by junjiejiangjjj** [comment]
Have the prerequisite dependencies been installed? You can refer to this: https://github.com/milvus-io/milvus-lite/blob/main/scripts/Dockerfile

**Comment by timspannzilliz** [comment]
I'll try but Raspberry Pi is Debian and not RHEL.   I'll check for equivalents

**Comment by Presburger** [comment]
'''
pip3 install conan==1.63.0
’‘’
please use conan 1.0

**Comment by timspannzilliz** [comment]
It did not work, also did not work for NVIDIA Ubuntu

**Comment by xiaofan-luan** [comment]
I don't think any of us tried to compile on debian with arm platform.

**Comment by xiaofan-luan** [comment]
Running it on this platform takes many efforts:
we need high gcc version, conan support on this platform and arm might also need special change

**Comment by Presburger** [comment]
During this period, we will try to release an arm64 version of the Python wheel package.
