### ISSUE TITLE
Can it support windows

### ISSUE THREAD

**Issue by dailinyucode** [milvus-io/milvus-lite#169]
it want to install this on window， but  he throw error in cmd， i don’t know this error，you can see
`Failed to create new connection using: c30557ae7328498e9fd0516d4195a0d2
Traceback (most recent call last):
  File "d:/project/milvus-demo/start.py", line 4, in <module>
    client = MilvusClient("./milvus_demo.db")
  File "D:\app\anaconda\envs\milvus-env\lib\site-packages\pymilvus\milvus_client\milvus_client.py", line 53, in __init__
    self._using = self._create_connection(
  File "D:\app\anaconda\envs\milvus-env\lib\site-packages\pymilvus\milvus_client\milvus_client.py", line 639, in _create_connection
    raise ex from ex
  File "D:\app\anaconda\envs\milvus-env\lib\site-packages\pymilvus\milvus_client\milvus_client.py", line 636, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "D:\app\anaconda\envs\milvus-env\lib\site-packages\pymilvus\orm\connections.py", line 403, in connect
    addr, parsed_uri = self.__get_full_address(*config)
  File "D:\app\anaconda\envs\milvus-env\lib\site-packages\pymilvus\orm\connections.py", line 259, in __get_full_address
    address, parsed = self.__parse_address_from_uri(uri)
  File "D:\app\anaconda\envs\milvus-env\lib\site-packages\pymilvus\orm\connections.py", line 176, in __parse_address_from_uri
    raise ConnectionConfigException(message=f"{illegal_uri_msg.format(uri)}") from None
pymilvus.exceptions.ConnectionConfigException: <ConnectionConfigException: (code=1, message=Illegal uri: [./milvus_demo.db], expected form 'http[s]://[user:password@]example.com[:12345]')>`
what i should do it? thanks!

**Comment by xiaofan-luan** [comment]
I'm not sure if milvus lite can support window(might not).
But the error might indicate you are using an old milvus version without milvus support.
Please try 2.4.4
