### ISSUE TITLE
No module named 'milvus_lite'

### ISSUE THREAD

**Issue by XiaoTongDeng** [milvus-io/milvus-lite#175]
i install pymilvus through command line :pip install pymilvus.
and then the following error occured:

>>> from pymilvus import MilvusClient
>>> client = MilvusClient("milvus_demo.db")
Failed to create new connection using: 52b63f487a1d40bfab3043360b0ccfd3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Anaconda\envs\kan\lib\site-packages\pymilvus\milvus_client\milvus_client.py", line 58, in __init__
    self._using = self._create_connection(
  File "E:\Anaconda\envs\kan\lib\site-packages\pymilvus\milvus_client\milvus_client.py", line 651, in _create_connection
    raise ex from ex
  File "E:\Anaconda\envs\kan\lib\site-packages\pymilvus\milvus_client\milvus_client.py", line 648, in _create_connection
    connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
  File "E:\Anaconda\envs\kan\lib\site-packages\pymilvus\orm\connections.py", line 378, in connect
    from milvus_lite.server_manager import server_manager_instance
ModuleNotFoundError: No module named 'milvus_lite'

**Comment by codingjaguar** [comment]
Hi Xiaotong, right now milvus-lite doesn't support native Windows install yet, but you can work around with wsl (https://learn.microsoft.com/en-us/windows/wsl/install), which is essentially Linux VM on windows.
We are actively working on supporting Windows natively, and would like to hear from your input! It'd be great if you can let us know what's your use case, e.g. for development, study purpose, or window based server deployment.

Thanks,
Jiang

**Comment by junjiejiangjjj** [comment]
#176

**Comment by junjiejiangjjj** [comment]
> > like to hear from your input! It'd be great if you can let us know what's your use case, e.g. for development, study purpose, or window based server deployment
> 
> My use case is that I just want to run the SDK library on Windows for development purposes. The Milvus server is on the Cloud.

On Windows, pymilvus 2.4.4 will not depend on milvus-lite, use `pip install pymilvus==2.4.4` to install.

**Comment by xiaofan-luan** [comment]
> > > like to hear from your input! It'd be great if you can let us know what's your use case, e.g. for development, study purpose, or window based server deployment
> > 
> > 
> > My use case is that I just want to run the SDK library on Windows for development purposes. The Milvus server is on the Cloud.
> 
> On Windows, pymilvus 2.4.4 will not depend on milvus-lite, use `pip install pymilvus==2.4.4` to install.

Do we support Milvus lite on window already?

**Comment by Eilok** [comment]
Although I install pymilvus 2.4.4, I still face the same error. What's wrong with this?

**Comment by junjiejiangjjj** [comment]
Is there an error log? I installed it successfully on Windows. Note that only pymilvus can be installed normally, and milvus-lite is still unavailable.
![image](https://github.com/user-attachments/assets/6fae76dd-11b7-4d9e-8491-037bdc7be127)

**Comment by Eilok** [comment]
> 是否有错误日志？我在 Windows 上成功安装了它。注意只有 pymilvus 可以正常安装，milvus-lite 仍然不可用。 ![图像](https://private-user-images.githubusercontent.com/14136703/349060389-6fae76dd-11b7-4d9e-8491-037bdc7be127.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNzg4OTEsIm5iZiI6MTcyMTE3ODU5MSwicGF0aCI6Ii8xNDEzNjcwMy8zNDkwNjAzODktNmZhZTc2ZGQtMTFiNy00ZDllLTg0OTEtMDM3YmRjN2JlMTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAxMDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMDQ0MzJlYmE1MjY1OTZjMDcwZmI0MzhiZWYzZmExZDhlYmI0N2Y1ZmQ3NzY5ODgzZTBmZDZkMGRiZjEyYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OIIMKFlpU7PqeL8uIqk52WuQSKYqxAt-uu8zMnM0tNk)

![屏幕截图 2024-07-17 091331](https://github.com/user-attachments/assets/e142f455-d73d-45cf-a69c-8a82e5c73d2a)
I have installed pymilvus 2.4.4 in Windows. Does it mean that milvus_lite can't be used in window?

**Comment by junjiejiangjjj** [comment]
Windows version is still under development.

**Comment by Eilok** [comment]
> Windows version is still under development.

Thank you~

**Comment by aswinthaikkat** [comment]
Sir , i am developing an application for a client which needs to work offline in windows. I am looking for embedddable vector databases. please say by when you guys will officialy support windows. else i would need to selelct alternate vector databse

**Comment by junjiejiangjjj** [comment]
> Sir , i am developing an application for a client which needs to work offline in windows. I am looking for embedddable vector databases. please say by when you guys will officialy support windows. else i would need to selelct alternate vector databse

It is already under development. We are currently solving some compilation issues on Windows, but it is difficult to estimate the specific completion time now.

**Comment by smartwhale8** [comment]
> It is already under development. We are currently solving some compilation issues on Windows, but it is difficult to estimate the specific completion time now.

Glad to read there is a fix under development. I encountered this issue after following the steps from https://milvus.io/docs/build-rag-with-milvus.md . Looking forward to the issue being fixed soon. Thank you!

**Comment by codenonsense** [comment]
i thought i was suffering alone from this problem

**Comment by codingjaguar** [comment]
The support of Milvus Lite on Windows is tracked by https://github.com/milvus-io/milvus-lite/issues/176. 

Let's use this issue to track the bug that **running pymilvus on windows failed**. This bug is fixed in https://github.com/milvus-io/milvus-lite/issues/175#issuecomment-2229864495. This means that running pymilvus with **milvus server** should work now. Running pymilvus with ** milvus lite locally on windows** doesn't work until  https://github.com/milvus-io/milvus-lite/issues/176 is fixed.

@XiaoTongDeng @JobaDiniz @smartwhale8 @codenonsense Could you please let us know that if "running pymilvus with **milvus server**" still fails?

> I encountered this issue after following the steps from https://milvus.io/docs/build-rag-with-milvus.md .
@smartwhale8 To run the demo you don't necessarily need milvus lite. The demo works for Milvus on [Docker](https://milvus.io/docs/install_standalone-docker.md) (very straightforward, just install docker deamon and run docker command) or K8s. Simply replacing the URI with the server endpoint of the milvus server deployed on docker or k8s.

**Comment by SohamTilekar** [comment]
Same Problem on My PC.

**Comment by siwaphatpg** [comment]
Same problem here.

**Comment by Rishi20-03-syfer** [comment]
I faced the same problem too but, I try this to establish connection
from pymilvus import connection

**Comment by lonngxiang** [comment]
pymilvus-2.4.6；为啥还报这个错误
 
![image](https://github.com/user-attachments/assets/0d91efc8-29d4-4d7b-8277-e20635028656)

**Comment by junjiejiangjjj** [comment]
hi @lonngxiang , milvus-lite does not support Windows yet, and compiling has encountered some difficulties

**Comment by Sun-ZhenXing** [comment]
Are there any plans for when windows will be officially supported? I'm really looking forward to it working properly on windows.
