### ISSUE TITLE
Milvus on Windows: 

### ISSUE THREAD

**Issue by PhilipPartsch** [milvus-io/milvus-lite#53]
I try to follow the instruction [here](https://milvus.io/docs/milvus_lite.md#Start-Milvus-Lite).
If I do so, I get
```
from milvus import default_server

from pymilvus import connections, utility

default_server.start()


    __  _________ _   ____  ______
   /  |/  /  _/ /| | / / / / / __/
  / /|_/ // // /_| |/ / /_/ /\ \
 /_/  /_/___/____/___/\____/___/ {Lite}

 Welcome to use Milvus!

 Version:   v2.2.6-lite
 Process:   27728
 Started:   2023-05-12 23:46:42
 Config:    C:\Users\xxxx\AppData\Roaming\milvus.io\milvus-server\2.2.6\configs\milvus.yaml
 Logs:      C:\Users\xxxx\AppData\Roaming\milvus.io\milvus-server\2.2.6\logs

 Ctrl+C to exit ...

connections.connect(host='127.0.0.1', port=default_server.listen_port)

print(utility.get_server_version())
[get_server_version] retry:4, cost: 0.27s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
grpc.RpcError
StatusCode.UNAVAILABLE
grpc.RpcError
StatusCode.UNAVAILABLE
grpc.RpcError
StatusCode.UNAVAILABLE
grpc.RpcError
StatusCode.UNAVAILABLE
[get_server_version] retry:5, cost: 0.81s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
grpc.RpcError
StatusCode.UNAVAILABLE
[get_server_version] retry:6, cost: 2.43s, reason: <_InactiveRpcError: StatusCode.UNAVAILABLE, internal: Milvus Proxy is not ready yet. please wait>
grpc.RpcError
StatusCode.UNAVAILABLE
Traceback (most recent call last):

  File ~\AppData\Roaming\Python\Python310\site-packages\pymilvus\decorators.py:50 in handler
    return func(self, *args, **kwargs)

  File ~\AppData\Roaming\Python\Python310\site-packages\pymilvus\client\grpc_handler.py:1224 in get_server_version
    resp = self._stub.GetVersion(req, timeout=timeout)

  File ~\AppData\Roaming\Python\Python310\site-packages\grpc\_channel.py:1030 in __call__
    return _end_unary_response_blocking(state, call, False, None)

  File ~\AppData\Roaming\Python\Python310\site-packages\grpc\_channel.py:910 in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "internal: Milvus Proxy is not ready yet. please wait"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:19530 {created_time:"2023-05-12T21:47:05.052105639+00:00", grpc_status:14, grpc_message:"internal: Milvus Proxy is not ready yet. please wait"}"
>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  Cell In[6], line 1
    print(utility.get_server_version())

  File ~\AppData\Roaming\Python\Python310\site-packages\pymilvus\orm\utility.py:950 in get_server_version
    return _get_connection(using).get_server_version(timeout=timeout)

  File ~\AppData\Roaming\Python\Python310\site-packages\pymilvus\decorators.py:109 in handler
    return func(*args, **kwargs)

  File ~\AppData\Roaming\Python\Python310\site-packages\pymilvus\decorators.py:140 in handler
    ret = func(self, *args, **kwargs)

  File ~\AppData\Roaming\Python\Python310\site-packages\pymilvus\decorators.py:75 in handler
    time.sleep(back_off)

KeyboardInterrupt
```

I tried to connect with a socket to default server, this was successful. 

In `milvus-stdout.log` I can find:
```
[2023/05/12 23:46:41.402 +02:00] [ERROR] [config/manager.go:181] ["Get configuration by items failed"] [error="etcdserver: leader changed"] [stack="github.com/milvus-io/milvus/internal/config.(*Manager).pullSourceConfigs\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/config/manager.go:181\ngithub.com/milvus-io/milvus/internal/config.(*Manager).AddSource\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/config/manager.go:163\ngithub.com/milvus-io/milvus/internal/config.Init\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/config/config.go:48\ngithub.com/milvus-io/milvus/internal/util/paramtable.(*BaseTable).initConfigsFromRemote\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/util/paramtable/base_table.go:169\ngithub.com/milvus-io/milvus/internal/util/paramtable.(*BaseTable).Init\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/util/paramtable/base_table.go:119\ngithub.com/milvus-io/milvus/internal/util/paramtable.(*ServiceParam).Init\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/util/paramtable/service_param.go:57\ngithub.com/milvus-io/milvus/internal/util/paramtable.(*ComponentParam).Init\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/util/paramtable/component_param.go:84\ngithub.com/milvus-io/milvus/internal/util/paramtable.(*ComponentParam).InitOnce.func1\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/util/paramtable/component_param.go:78\nsync.(*Once).doSlow\n\tD:/a/_temp/msys64/mingw64/lib/go/src/sync/once.go:68\nsync.(*Once).Do\n\tD:/a/_temp/msys64/mingw64/lib/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/util/paramtable.(*ComponentParam).InitOnce\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/util/paramtable/component_param.go:77\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/cmd/roles/roles.go:86"]
```
What I wondering is:
I do not have a folder `a` on drive `D:`. I believe there is a configuration issue in the etcd on windows machines. 

Does any body has some hints?

**Comment by matrixji** [comment]
If the `xxxx` here contains a non-ASCII character. it may fail, as Windows-based Milvus is not compiled with Unicode support.
You could try `default_server.set_base_dir('milvus_data')` before the start.

**Comment by qdx1997** [comment]
没有解决这个问题

**Comment by matrixji** [comment]
> 没有解决这个问题

Could you provide more logs or output screenshots?

**Comment by qdx1997** [comment]
我是在windows python3.9.5上运行的，没有安装milvus，是否需要安装其他东西





763004560
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "milvus-io/milvus-lite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月25日(星期四) 晚上6:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [milvus-io/milvus-lite] Milvus on Windows:  (Issue #53)





  
没有解决这个问题
  
Could you provide more logs or output screenshots?

**Comment by matrixji** [comment]
The banner already shows:
    __  _________ _   ____  ______
   /  |/  /  _/ /| | / / / / / __/
  / /|_/ // // /_| |/ / /_/ /\ \
 /_/  /_/___/____/___/\____/___/ {Lite}

 Welcome to use Milvus!

 Version:   v2.2.6-lite
 Process:   27728
 Started:   2023-05-12 23:46:42
 Config:    C:\Users\xxxx\AppData\Roaming\milvus.io\milvus-server\2.2.6\configs\milvus.yaml
 Logs:      C:\Users\xxxx\AppData\Roaming\milvus.io\milvus-server\2.2.6\logs

So the logs should be in folder: C:\Users\xxxx\AppData\Roaming\milvus.io\milvus-server\2.2.6\logs

**Comment by Cyberhan123** [comment]
I use the cli cmd, but got error.

```bash
 milvus-server --data milvus_data --debug
```
And the error log is:
```log
[2023/11/03 17:33:05.528 +08:00] [INFO] [paramtable/quota_param.go:780] ["init disk quota"] [diskQuota(MB)=+inf]
[2023/11/03 17:33:05.543 +08:00] [INFO] [paramtable/quota_param.go:795] ["init disk quota per DB"] [diskQuotaPerCollection(MB)=1.7976931348623157e+308]
[2023/11/03 17:33:05.544 +08:00] [INFO] [paramtable/component_param.go:1578] ["init segment max idle time"] [value=10m0s]
[2023/11/03 17:33:05.544 +08:00] [INFO] [paramtable/component_param.go:1583] ["init segment min size from idle to sealed"] [value=16]
[2023/11/03 17:33:05.544 +08:00] [INFO] [paramtable/component_param.go:1593] ["init segment max binlog file to sealed"] [value=32]
[2023/11/03 17:33:05.544 +08:00] [INFO] [paramtable/component_param.go:1588] ["init segment expansion rate"] [value=1.25]
[2023/11/03 17:33:05.545 +08:00] [INFO] [paramtable/base_table.go:145] ["cannot find etcd.endpoints"]
[2023/11/03 17:33:05.545 +08:00] [INFO] [paramtable/hook_config.go:19] ["hook config"] [hook={}]
2023/11/03 17:33:05 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined

    __  _________ _   ____  ______
   /  |/  /  _/ /| | / / / / / __/
  / /|_/ // // /_| |/ / /_/ /\ \
 /_/  /_/___/____/___/\____/___/

Welcome to use Milvus!
Version:   v2.2.14-lite
Built:     Sat, Sep  2, 2023  2:26:30 PM
GitCommit: b34d40967
GoVersion: go version go1.18 windows/amd64

open pid file: run/standalone.pid
lock pid file: run/standalone.pid
[2023/11/03 17:33:05.551 +08:00] [INFO] [roles/roles.go:228] ["starting running Milvus components"]
[2023/11/03 17:33:05.554 +08:00] [INFO] [paramtable/quota_param.go:780] ["init disk quota"] [diskQuota(MB)=+inf]
[2023/11/03 17:33:05.554 +08:00] [INFO] [paramtable/quota_param.go:795] ["init disk quota per DB"] [diskQuotaPerCollection(MB)=1.7976931348623157e+308]
[2023/11/03 17:33:05.555 +08:00] [INFO] [paramtable/component_param.go:1578] ["init segment max idle time"] [value=10m0s]
[2023/11/03 17:33:05.555 +08:00] [INFO] [paramtable/component_param.go:1583] ["init segment min size from idle to sealed"] [value=16]
[2023/11/03 17:33:05.555 +08:00] [INFO] [paramtable/component_param.go:1593] ["init segment max binlog file to sealed"] [value=32]
[2023/11/03 17:33:05.555 +08:00] [INFO] [paramtable/component_param.go:1588] ["init segment expansion rate"] [value=1.25]
[2023/11/03 17:33:05.555 +08:00] [INFO] [paramtable/base_table.go:145] ["cannot find etcd.endpoints"]
[2023/11/03 17:33:05.555 +08:00] [INFO] [paramtable/hook_config.go:19] ["hook config"] [hook={}]
[2023/11/03 17:33:05.558 +08:00] [INFO] [server/global_rmq.go:55] ["initializing global rmq"] [path="D:\\learn\\milvus\\milvus_data\\data\\rocketmq"]
[2023/11/03 17:33:05.558 +08:00] [INFO] [server/rocksmq_impl.go:154] ["Start rocksmq "] ["max proc"=8] [parallism=1] ["lru cache"=2047383797]
[2023/11/03 17:33:05.612 +08:00] [INFO] [tso/tso.go:121] ["sync and save timestamp"] [last=2023/11/03 17:32:29.852 +08:00] [save=2023/11/03 17:33:08.612 +08:00] [next=2023/11/03 17:33:05.612 +08:00]
[2023/11/03 17:33:05.613 +08:00] [INFO] [server/rocksmq_retention.go:99] ["Rocksmq retention goroutine start!"]
[2023/11/03 17:33:05.622 +08:00] [ERROR] [etcd/etcd_server.go:62] ["failed to init embedded Etcd server"] [error="listen tcp 127.0.0.1:2379: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."] [stack="github.com/milvus-io/milvus/internal/util/etcd.InitEtcdServer.func1\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/util/etcd/etcd_server.go:62\nsync.(*Once).doSlow\n\tD:/a/_temp/msys64/mingw64/lib/go/src/sync/once.go:68\nsync.(*Once).Do\n\tD:/a/_temp/msys64/mingw64/lib/go/src/sync/once.go:59\ngithub.com/milvus-io/milvus/internal/util/etcd.InitEtcdServer\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/util/etcd/etcd_server.go:39\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/cmd/roles/roles.go:252\ngithub.com/milvus-io/milvus/cmd/milvus.(*run).execute\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/cmd/milvus/run.go:117\ngithub.com/milvus-io/milvus/cmd/milvus.RunMilvus\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/cmd/milvus/milvus.go:60\nmain.main\n\tD:/a/milvus-lite/milvus-lite/milvus_binary/milvus/cmd/main.go:26\nruntime.main\n\tD:/a/_temp/msys64/mingw64/lib/go/src/runtime/proc.go:250"]
[2023/11/03 17:33:05.622 +08:00] [INFO] [etcd/etcd_server.go:66] ["finish init Etcd config"] [path=] [data="D:\\learn\\milvus\\milvus_data\\data\\etcd.data"]
[2023/11/03 17:33:05.622 +08:00] [INFO] [management/server.go:68] ["management listen"] [addr=:9092]
[2023/11/03 17:33:05.638 +08:00] [INFO] [paramtable/quota_param.go:780] ["init disk quota"] [diskQuota(MB)=+inf]
[2023/11/03 17:33:05.638 +08:00] [INFO] [paramtable/quota_param.go:795] ["init disk quota per DB"] [diskQuotaPerCollection(MB)=1.7976931348623157e+308]
[2023/11/03 17:33:05.638 +08:00] [INFO] [paramtable/component_param.go:1578] ["init segment max idle time"] [value=10m0s]
[2023/11/03 17:33:05.638 +08:00] [INFO] [paramtable/component_param.go:1583] ["init segment min size from idle to sealed"] [value=16]
[2023/11/03 17:33:05.638 +08:00] [INFO] [paramtable/component_param.go:1593] ["init segment max binlog file to sealed"] [value=32]
[2023/11/03 17:33:05.638 +08:00] [INFO] [paramtable/component_param.go:1588] ["init segment expansion rate"] [value=1.25]
[2023/11/03 17:33:05.638 +08:00] [INFO] [paramtable/base_table.go:145] ["cannot find etcd.endpoints"]
[2023/11/03 17:33:05.638 +08:00] [INFO] [paramtable/hook_config.go:19] ["hook config"] [hook={}]
[2023/11/03 17:33:05.639 +08:00] [INFO] [rootcoord/root_coord.go:176] ["update rootcoord state"] [state=Abnormal]
[2023/11/03 17:33:05.641 +08:00] [INFO] [paramtable/quota_param.go:780] ["init disk quota"] [diskQuota(MB)=+inf]
[2023/11/03 17:33:05.641 +08:00] [INFO] [paramtable/quota_param.go:795] ["init disk quota per DB"] [diskQuotaPerCollection(MB)=1.7976931348623157e+308]
[2023/11/03 17:33:05.641 +08:00] [INFO] [paramtable/component_param.go:1578] ["init segment max idle time"] [value=10m0s]
[2023/11/03 17:33:05.642 +08:00] [INFO] [paramtable/component_param.go:1583] ["init segment min size from idle to sealed"] [value=16]
[2023/11/03 17:33:05.642 +08:00] [INFO] [paramtable/component_param.go:1593] ["init segment max binlog file to sealed"] [value=32]
[2023/11/03 17:33:05.642 +08:00] [INFO] [paramtable/component_param.go:1588] ["init segment expansion rate"] [value=1.25]
[2023/11/03 17:33:05.642 +08:00] [INFO] [paramtable/base_table.go:145] ["cannot find etcd.endpoints"]
[2023/11/03 17:33:05.642 +08:00] [INFO] [paramtable/hook_config.go:19] ["hook config"] [hook={}]
[2023/11/03 17:33:05.642 +08:00] [DEBUG] [proxy/multi_rate_limiter.go:331] ["RateLimiter register for rateType"] [rateType=DMLDelete] [rate=+inf] [burst=1.7976931348623157e+308]
[2023/11/03 17:33:05.643 +08:00] [DEBUG] [proxy/multi_rate_limiter.go:331] ["RateLimiter register for rateType"] [rateType=DQLSearch] [rate=+inf] [burst=1.7976931348623157e+308]
[2023/11/03 17:33:05.643 +08:00] [DEBUG] [proxy/service.go:122] ["create a new Proxy instance"] [module=Proxy] [state=Abnormal]
[2023/11/03 17:33:05.643 +08:00] [INFO] [proxy/service.go:360] ["init Proxy server"]
[2023/11/03 17:33:05.644 +08:00] [DEBUG] [paramtable/grpc_param.go:153] [initServerMaxSendSize] [role=rootcoord] [grpc.serverMaxSendSize=536870912]
[2023/11/03 17:33:05.644 +08:00] [DEBUG] [paramtable/grpc_param.go:175] [initServerMaxRecvSize] [role=rootcoord] [grpc.serverMaxRecvSize=536870912]
[2023/11/03 17:33:05.644 +08:00] [INFO] [rootcoord/service.go:176] ["init params done.."]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x7ff716bb815b]

goroutine 186 [running]:
github.com/milvus-io/milvus/internal/util/etcd.GetEmbedEtcdClient(...)
        D:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/util/etcd/etcd_server.go:25
github.com/milvus-io/milvus/internal/util/etcd.GetEtcdClient(0x78?, 0x1d?, {0x0?, 0xc000d3c0c0?, 0xc00051b700?}, {0xc00070adc8?, 0x1?}, {0xc000d15ca0?, 0x7ff71664e8eb?}, {0xc0002fb480, ...}, ...)
        D:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/util/etcd/etcd_util.go:48 +0x9b
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).init(0xc00036e9a0)
        D:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/distributed/rootcoord/service.go:181 +0x18e
github.com/milvus-io/milvus/internal/distributed/rootcoord.(*Server).Run(0xc000231f08?)
        D:/a/milvus-lite/milvus-lite/milvus_binary/milvus/internal/distributed/rootcoord/service.go:158 +0x25
github.com/milvus-io/milvus/cmd/components.(*RootCoord).Run(0x7ff71a1e6400?)
        D:/a/milvus-lite/milvus-lite/milvus_binary/milvus/cmd/components/root_coord.go:56 +0x2f
github.com/milvus-io/milvus/cmd/roles.runComponent[...].func1()
        D:/a/milvus-lite/milvus-lite/milvus_binary/milvus/cmd/roles/roles.go:120 +0x185
created by github.com/milvus-io/milvus/cmd/roles.runComponent[...]
        D:/a/milvus-lite/milvus-lite/milvus_binary/milvus/cmd/roles/roles.go:104 +0x18a
Wait for milvus server started timeout.
```
