### ISSUE TITLE
Milvus Lite will not start on M1 Mac

### ISSUE THREAD

**Issue by PhilLovesToCode** [milvus-io/milvus-lite#69]
I am trying to start Milvus from within Python as follows:
```python
from milvus import default_server
default_server.cleanup()
default_server.start()
```
It just hangs on default_server.start(), then times out after 180 seconds.  When I run `debug_server.start()`, I get the error shown below.  It appears to have something to do with the embedded etcd.  Is etcd failing to start?  Or could it be that something in MacOS is blocking Milvus' connection to its own etcd?
```log
2023/09/13 10:04:19 maxprocs: Leaving GOMAXPROCS=10: CPU quota undefined
Set runtime dir at /run/milvus failed, set it to /tmp/milvus directory

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Version:   v2.2-testing-20230824-68-ga34a9d606-lite
Built:     Mon Sep  4 06:25:13 UTC 2023
GitCommit: a34a9d606
GoVersion: go version go1.21.0 darwin/arm64

open pid file: /tmp/milvus/standalone.pid
lock pid file: /tmp/milvus/standalone.pid
[2023/09/13 10:04:19.940 -05:00] [INFO] [roles/roles.go:288] ["starting running Milvus components"]
[2023/09/13 10:04:19.946 -05:00] [INFO] [config/refresher.go:66] ["start refreshing configurations"] [source=FileSource]
[2023/09/13 10:04:19.947 -05:00] [INFO] [config/refresher.go:66] ["start refreshing configurations"] [source=FileSource]
[2023/09/13 10:04:19.947 -05:00] [INFO] [etcd/etcd_util.go:49] ["create etcd client"] [useEmbedEtcd=false] [useSSL=false] [endpoints="[localhost:2379]"] [minVersion=1.3]
{"level":"warn","ts":"2023-09-13T10:04:22.952-0500","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0x14000bfae00/localhost:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:2379: connect: connection refused\""}
[2023/09/13 10:04:22.952 -05:00] [ERROR] [config/manager.go:250] ["Get configuration by items failed"] [error="context deadline exceeded"] [stack="github.com/milvus-io/milvus/pkg/config.(*Manager).pullSourceConfigs\n\t/Users/jibin/Working/milvus-lite/milvus_binary/milvus/pkg/config/manager.go:250\ngithub.com/milvus-io/milvus/pkg/config.(*Manager).AddSource\n\t/Users/jibin/Working/milvus-lite/milvus_binary/milvus/pkg/config/manager.go:187\ngithub.com/milvus-io/milvus/pkg/util/paramtable.(*BaseTable).initConfigsFromRemote\n\t/Users/jibin/Working/milvus-lite/milvus_binary/milvus/pkg/util/paramtable/base_table.go:162\ngithub.com/milvus-io/milvus/pkg/util/paramtable.(*BaseTable).init\n\t/Users/jibin/Working/milvus-lite/milvus_binary/milvus/pkg/util/paramtable/base_table.go:117\ngithub.com/milvus-io/milvus/pkg/util/paramtable.(*hookConfig).init\n\t/Users/jibin/Working/milvus-lite/milvus_binary/milvus/pkg/util/paramtable/hook_config.go:20\ngithub.com/milvus-io/milvus/pkg/util/paramtable.(*ComponentParam).init\n\t/Users/jibin/Working/milvus-lite/milvus_binary/milvus/pkg/util/paramtable/component_param.go:121\ngithub.com/milvus-io/milvus/pkg/util/paramtable.(*ComponentParam).Init.func1\n\t/Users/jibin/Working/milvus-lite/milvus_binary/milvus/pkg/util/paramtable/component_param.go:98\nsync.(*Once).doSlow\n\t/opt/homebrew/Cellar/go/1.21.0/libexec/src/sync/once.go:74\nsync.(*Once).Do\n\t/opt/homebrew/Cellar/go/1.21.0/libexec/src/sync/once.go:65\ngithub.com/milvus-io/milvus/pkg/util/paramtable.(*ComponentParam).Init\n\t/Users/jibin/Working/milvus-lite/milvus_binary/milvus/pkg/util/paramtable/component_param.go:97\ngithub.com/milvus-io/milvus/pkg/util/paramtable.Init\n\t/Users/jibin/Working/milvus-lite/milvus_binary/milvus/pkg/util/paramtable/runtime.go:29\ngithub.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run\n\t/Users/jibin/Working/milvus-lite/milvus_binary/milvus/cmd/roles/roles.go:300\ngithub.com/milvus-io/milvus/cmd/milvus.(*run).execute\n\t/Users/jibin/Working/milvus-lite/milvus_binary/milvus/cmd/milvus/run.go:117\ngithub.com/milvus-io/milvus/cmd/milvus.RunMilvus\n\t/Users/jibin/Working/milvus-lite/milvus_binary/milvus/cmd/milvus/milvus.go:60\nmain.main\n\t/Users/jibin/Working/milvus-lite/milvus_binary/milvus/cmd/main.go:26\nruntime.main\n\t/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/proc.go:267"]
```

**Comment by matrixji** [comment]
The etcd is started after several seconds, so we could ignore the initial connection failure with etcd.
More logs should be in folder `~/.milvus.io/milvus-server/2.3.0/logs` , if possible, could share some ERROR logs under it for continued investigations?

**Comment by stephen37** [comment]
Hey, 
It seems like I have a similar problem when using milvus-lite. 
```python
from milvus import debug_server

debug_server.start()
```
I also get a timeout and then an error related to an IO error as you can see in the error 

```
2023/10/04 20:30:22 maxprocs: Leaving GOMAXPROCS=10: CPU quota undefined
Set runtime dir at /run/milvus failed, set it to /tmp/milvus directory

    __  _________ _   ____  ______    
   /  |/  /  _/ /| | / / / / / __/    
  / /|_/ // // /_| |/ / /_/ /\ \    
 /_/  /_/___/____/___/\____/___/     

Welcome to use Milvus!
Version:   v2.2.14-lite
Built:     Sat Sep  2 14:37:00 UTC 2023
GitCommit: b34d40967
GoVersion: go version go1.21.0 darwin/arm64

open pid file: /tmp/milvus/standalone.pid
lock pid file: /tmp/milvus/standalone.pid
panic: IO error: While lock file: /Users/stephenbatifol/.milvus.io/milvus-server/2.2.14/data/rocketmq_meta_kv/LOCK: Resource temporarily unavailable

goroutine 1 [running]:
github.com/milvus-io/milvus/cmd/roles.(*MilvusRoles).Run(0x14000ca7df0, 0x1, {0x0, 0x0})
	/Users/jibin/Working/milvus-lite-2.2/milvus_binary/milvus/cmd/roles/roles.go:245 +0xa1c
github.com/milvus-io/milvus/cmd/milvus.(*run).execute(0x1400097df80, {0x14000118750?, 0x3, 0x3}, 0x14000893b90)
	/Users/jibin/Working/milvus-lite-2.2/milvus_binary/milvus/cmd/milvus/run.go:117 +0x684
github.com/milvus-io/milvus/cmd/milvus.RunMilvus({0x14000118750?, 0x3, 0x3})
	/Users/jibin/Working/milvus-lite-2.2/milvus_binary/milvus/cmd/milvus/milvus.go:60 +0x238
main.main()
	/Users/jibin/Working/milvus-lite-2.2/milvus_binary/milvus/cmd/main.go:26 +0x34
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
Cell In[11], line 3
      1 from milvus import debug_server
----> 3 debug_server.start()

File ~/Documents/<path>/.venv/lib/python3.10/site-packages/milvus/__init__.py:427, in MilvusServer.start(self)
    425 os.chdir(old_pwd)
    426 if self.wait_for_started:
--> 427     self.wait_started()
    428 if not self._debug:
    429     self.show_banner()

File ~/Documents/<path>/.venv/lib/python3.10/site-packages/milvus/__init__.py:391, in MilvusServer.wait_started(self, timeout)
    389         sleep(0.1)
    390 if self.running:
--> 391     raise TimeoutError(f'Milvus not startd in {timeout/1000} seconds')
    392 else:
    393     raise RuntimeError('Milvus server already stopped')

TimeoutError: Milvus not startd in 30.0 seconds
```

I have tried different versions of milvus-lite, different versions of Python as well and the problem seems to persist.

**Comment by soujie** [comment]
I had the same problem: I couldn't start server on M1 pro mac, but work on ubuntu 18.04. :)
